import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { readFile, writeFile } from 'node:fs/promises'
const require = createRequire(new URL('../../../../CRM-Avance-Corp/app/package.json', import.meta.url))
const evidencia = nombre => fileURLToPath(new URL(nombre, import.meta.url))
const { chromium, expect } = require('@playwright/test')
const browser = await chromium.launch({ headless: true })
const errores = []
const pruebas = []
const contexto = await browser.newContext({ viewport: { width: 1672, height: 941 }, deviceScaleFactor: 1, reducedMotion: 'reduce', acceptDownloads: true })
const page = await contexto.newPage()
page.on('pageerror', error => errores.push(error.message))
page.on('console', mensaje => { if (mensaje.type() === 'error') errores.push(mensaje.text()) })
const tabla = () => page.getByRole('table', { name: 'Resultados por analista de las citas filtradas' })
try {
  await page.goto(process.env.CITAS_QA_URL ?? 'http://127.0.0.1:4180/prototypes/citas-crm.html')
  await page.evaluate(() => document.fonts.ready)
  await expect(page.getByRole('tab', { name: 'Resultados' })).toHaveAttribute('aria-selected', 'true')
  await expect(tabla().getByRole('row', { name: /Total de la consulta/ })).toContainText('51.3%')
  await page.screenshot({ path: evidencia('tablero.png') })
  await page.getByRole('button', { name: 'Depositó 1', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Personas del flujo de recuperación' }).getByRole('row')).toHaveCount(2)
  await expect(tabla().getByRole('row', { name: /Total de la consulta/ })).toContainText('40 / 26')
  await page.getByRole('button', { name: 'No asistieron 4', exact: true }).click()
  await page.getByRole('button', { name: 'Ver recorrido de Andrea Peralta' }).click()
  const ficha = page.getByRole('dialog', { name: 'Andrea Peralta' })
  await expect(page.locator('[data-slot=sheet-overlay]')).toHaveCount(0)
  await expect(ficha).toContainText('2 citas · 66.7% de la meta')
  await expect(ficha).toContainText('10:00')
  await expect(ficha).toContainText('10:05 Lima')
  await page.screenshot({ path: evidencia('ficha-andrea.png') })
  const geometria = await page.evaluate(() => ({
    viewport: [innerWidth, innerHeight], documento: [document.documentElement.scrollWidth, document.documentElement.scrollHeight],
    ficha: document.querySelector('[role="dialog"]').getBoundingClientRect().toJSON(),
    tablas: [...document.querySelectorAll('table')].map(t => ({ titulo: t.caption?.innerText, rect: t.getBoundingClientRect().toJSON() })),
    fuente: getComputedStyle(document.querySelector('.citas-crm')).fontFamily,
    seleccion: getComputedStyle(document.querySelector('.citas-fila-seleccionada')).backgroundColor,
  }))
  expect(geometria.documento[0]).toBe(1672)
  expect(geometria.tablas.at(-1).rect.bottom).toBeLessThanOrEqual(941)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Ver recorrido de Andrea Peralta' })).toBeFocused()
  pruebas.push('Flujo 4/3/1/1 y base 40/26 conservada al elegir etapa; ficha no modal, meta y fechas; Escape devuelve foco; tablas completas a 1672x941')
  await page.getByRole('button', { name: 'Ver recorrido de Mónica Silva' }).click()
  await page.getByRole('combobox', { name: 'Analista', exact: true }).focus()
  await page.getByRole('combobox', { name: 'Analista', exact: true }).selectOption('valeria')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Analista', exact: true })).toBeFocused()
  await expect(tabla().getByRole('row', { name: /Total de la consulta/ })).toContainText('6 / 4')
  await page.getByRole('combobox', { name: 'Semana', exact: true }).selectOption('1')
  await expect(page.getByRole('table', { name: 'Personas del flujo de recuperación' })).toContainText('09 set. 2026')
  await page.getByRole('combobox', { name: 'Semana', exact: true }).selectOption('4')
  await expect(page.getByText('No hay citas con esta combinación')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Exportar citas' })).toBeDisabled()
  await page.getByRole('button', { name: 'Restablecer consulta' }).click()
  await page.getByRole('combobox', { name: 'Mes', exact: true }).selectOption('2026-08')
  await expect(page.getByText('No hay citas con esta combinación')).toBeVisible()
  await page.getByRole('button', { name: 'Restablecer consulta' }).click()
  pruebas.push('Cambio de analista cierra la ficha sin robar foco; semana 1 conserva seguimiento de nueva cita en semana 2; semana 4 y agosto muestran vacío y exportación inhabilitada')
  await page.getByText('Columnas', { exact: true }).click()
  await page.getByLabel('Leads con 2+ citas', { exact: true }).check()
  await page.getByLabel('Realizadas', { exact: true }).check()
  await expect(tabla().getByRole('columnheader', { name: 'Leads con 2+ citas' })).toBeVisible()
  await expect(tabla().getByRole('columnheader', { name: 'Realizadas' })).toBeVisible()
  await page.getByText('Columnas', { exact: true }).click()
  await page.getByRole('button', { name: 'Más filtros', exact: true }).click()
  await page.getByRole('checkbox', { name: /No asist/ }).check()
  await expect(tabla().getByRole('row', { name: /Total de la consulta/ })).toContainText('4 / 4')
  await page.getByRole('tab', { name: 'Bandeja comercial' }).click()
  await expect(page.getByTestId('conteo-citas')).toContainText('4 de 40')
  await page.getByRole('tab', { name: 'Bandeja comercial' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Agenda' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('conteo-citas')).toContainText('4 de 40')
  await page.getByRole('button', { name: 'Restablecer consulta' }).click()
  await page.getByRole('tab', { name: 'Bandeja comercial' }).click()
  await page.getByRole('button', { name: 'Página siguiente' }).click()
  const descarga = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar citas' }).click()
  const archivo = await descarga
  const csv = await readFile(await archivo.path(), 'utf8')
  expect(csv.split('\r\n')).toHaveLength(41)
  pruebas.push('Columnas opcionales; filtro de estado conserva datos entre bandeja/agenda/resultados; navegación de pestañas por teclado; CSV de las 40 citas desde página 2')
  await page.getByRole('tab', { name: 'Resultados' }).click()
  const masFiltros = page.getByRole('button', { name: 'Más filtros', exact: true })
  if (await masFiltros.getAttribute('aria-expanded') === 'true') await masFiltros.click()
  await page.getByRole('button', { name: 'Ver recorrido de Andrea Peralta' }).click()
  await page.getByRole('button', { name: 'Ver cita vinculada' }).click()
  await expect(page.getByRole('button', { name: 'Ubicar en agenda' })).toBeVisible()
  await page.getByRole('button', { name: 'Ubicar en agenda' }).click()
  await expect(page.getByTestId('conteo-citas')).toContainText('1 de 40')
  pruebas.push('Recorrido -> cita vinculada -> agenda operable')
  await page.getByRole('button', { name: 'Restablecer consulta' }).click()
  await page.getByRole('tab', { name: 'Resultados' }).click()
  await expect(page.locator('[data-slot=sheet]')).toHaveCount(0)
  for (const width of [1280, 1024, 768]) {
    await page.setViewportSize({ width, height: 941 })
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    const pasos = await page.evaluate(() => [...document.querySelectorAll('.citas-flujo-etapa')].map(n => ({ boton: n.querySelector('button').getBoundingClientRect().toJSON(), flecha: n.querySelector('svg')?.getBoundingClientRect().toJSON() })))
    pasos.forEach((paso, indice) => { if (paso.flecha) { expect(paso.boton.right).toBeLessThanOrEqual(paso.flecha.left); expect(paso.flecha.right).toBeLessThanOrEqual(pasos[indice + 1].boton.left) } })
  }
  await page.screenshot({ path: evidencia('tablet.png'), fullPage: true })
  pruebas.push('1280, 1024 y 768 px sin desborde de página')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await page.screenshot({ path: evidencia('movil.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await page.getByRole('button', { name: 'Ver recorrido de Mónica Silva' }).click()
  const movil = page.getByRole('dialog', { name: 'Mónica Silva' })
  await expect(page.locator('[data-slot=sheet-overlay]')).toBeVisible()
  await expect(movil).toContainText('Asistencia pendiente')
  const caja = await movil.boundingBox()
  expect(caja.width).toBe(390)
  await page.screenshot({ path: evidencia('movil-ficha.png') })
  for (let i = 0; i < 6; i++) await page.keyboard.press('Tab')
  expect(await movil.evaluate(nodo => nodo.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(movil).toHaveCount(0)
  pruebas.push('Móvil 390x844 sin desborde de página; tablas con desplazamiento propio; ficha de ancho completo, foco contenido y cierre con Escape')
  expect(errores).toEqual([])
  await writeFile(evidencia('interacciones.json'), JSON.stringify({ resultado: 'PASS', pruebas, errores, geometria }, null, 2))
  console.log(JSON.stringify({ resultado: 'PASS', pruebas, errores, geometria }, null, 2))
} finally { await browser.close() }
