import { expect, test } from '@playwright/test'
import { loginReal, montarBackendReal } from './_helpers'
import { montarConsultaCitas } from './_citas'

test('avance mensual: fuentes, filtros, recorrido, monedas y detalle', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-04T15:00:00Z'))
  await montarBackendReal(page)
  await montarConsultaCitas(page, undefined, 'mensual')
  await loginReal(page)
  await page.getByRole('button', { name: 'Citas', exact: true }).click()
  const tabla = page.getByRole('table', { name: /Leads, citas, entrevistas, conversión/ })
  const fila = tabla.getByRole('row', { name: /ANALISTA DE PRUEBA/ })
  await expect(fila).toContainText('60%')
  await expect(fila).toContainText('33.3%')
  await expect(tabla.getByRole('row', { name: /ANALISTA SIN CITAS/ })).toContainText('0%')
  await expect(page.getByRole('region', { name: 'Tabla de personas del flujo' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Se hicieron clientes 1', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Tabla de personas del flujo' })).toContainText('Convertido a cliente')
  await page.getByRole('button', { name: 'Ocultar personas' }).click()
  await page.getByLabel('Semana', { exact: true }).selectOption('4')
  await expect(fila).toContainText('60%')
  await expect(page.getByText('Esta tabla conserva el acumulado mensual', { exact: false })).toBeVisible()
  await page.getByLabel('Moneda de los importes reales').selectOption('USD')
  await expect(fila).toContainText('1,000')
  await page.getByRole('button', { name: /ANALISTA SIN CITAS/, exact: false }).click()
  const detalle = page.getByRole('dialog')
  await expect(detalle).toContainText('1 leads de registro manual')
  await detalle.getByRole('button', { name: 'Ver leads y citas' }).click()
  await expect(detalle).toContainText('PERSONA DE PRUEBA 14')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Más filtros/ }).click()
  await page.getByLabel('Tipo de registro').selectOption('manual')
  await expect(tabla.getByRole('row', { name: /ANALISTA DE PRUEBA/ })).toHaveCount(0)
  await expect(tabla.getByRole('row', { name: /ANALISTA SIN CITAS/ })).toBeVisible()
  await page.getByRole('button', { name: 'Restablecer consulta' }).click()
  const descarga = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar avance' }).click()
  expect((await descarga).suggestedFilename()).toBe('citas-avance-2026-09-USD.csv')
  await page.getByRole('button', { name: /Más filtros/ }).click()
  for (const width of [1440, 1280, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: `/private/tmp/citas-avance-crm-${width}.png`, fullPage: true })
  }
})
