import { expect, test, type Page } from '@playwright/test'
import { loginReal, montarBackendReal, leadReal, UID } from './_helpers'
import fixture from '../src/lib/gestion-diaria-f5.test.fixture.json' with { type: 'json' }
import { diaEquipoPrueba, filaEquipoPrueba } from '../src/lib/gestion-diaria-equipo.fixture'

// Transporte interceptado sobre respuestas SQL sintéticas reales. No prueba
// por sí solo Auth/RLS: las 18 solicitudes PostgREST del banco cubren esa capa.
const DIA = '2026-09-23'
const grupo = fixture.pulso.equipos.find((e) => e.metricas.llamadas === 4)!
const analista = grupo.personas.find((p) => p.activo && p.llamadas === 4)!
const cliente = leadReal({ vendedor_id: analista.analista_id!, nombre_completo: 'CLIENTE FICTICIO F5' })
function moverFechas<T>(foto: T, dia: string): T {
  const diferencia = Date.parse(`${dia}T00:00:00Z`) - Date.parse(`${DIA}T00:00:00Z`)
  return JSON.parse(JSON.stringify(foto), (clave, valor) => {
    if (typeof valor !== 'string' || !/^\d{4}-\d{2}-\d{2}(T|$)/.test(valor) || ['generado_en', 'pendientes_al'].includes(clave)) return valor
    const nueva = new Date(Date.parse(`${valor.slice(0, 10)}T00:00:00Z`) + diferencia).toISOString().slice(0, 10)
    return nueva + valor.slice(10)
  })
}
async function montar(page: Page) {
  await page.setViewportSize({ width: 1512, height: 900 })
  await page.clock.setFixedTime(new Date('2026-09-24T21:00:00Z'))
  await montarBackendReal(page, { rolCrm: 'gerencia', leads: [cliente], tareas: [] })
  await page.addInitScript(({ actor, dia }) => {
    const clave = `avancecorp:gestion-diaria:f5:dia:${actor}`
    if (sessionStorage.getItem(clave) === null) sessionStorage.setItem(clave, dia)
  }, { actor: UID, dia: DIA })
  const estado = { error: false, revocado: false, registroRevocado: false, paginado: false, dias: [] as string[], periodos: [] as number[], registros: [] as Record<string, unknown>[] }
  await page.route('**/rest/v1/rpc/gestion_diaria_pulso_fn', async (route) => {
    const { p_dia } = route.request().postDataJSON(); estado.dias.push(p_dia)
    if (estado.revocado) return route.fulfill({ status: 403, json: { code: '42501', message: 'Acceso revocado' } })
    if (estado.error) return route.fulfill({ status: 400, json: { code: 'XX000', message: 'Fallo controlado' } })
    return route.fulfill({ json: moverFechas(fixture.pulso, p_dia) })
  })
  await page.route('**/rest/v1/rpc/gestion_diaria_habitos_fn', async (route) => {
    const { p_hasta, p_dias } = route.request().postDataJSON(); estado.periodos.push(p_dias)
    return route.fulfill({ json: moverFechas(p_dias === 7 ? fixture.habitos : p_dias === 14 ? fixture.habitos14 : fixture.habitos30, p_hasta) })
  })
  await page.route('**/rest/v1/rpc/gestion_diaria_equipo_fn', async (route) => {
    const pedido = route.request().postDataJSON()
    expect(pedido.p_supervisor_id).toBeUndefined()
    return route.fulfill({ json: moverFechas(fixture.equipo, pedido.p_dia) })
  })
  await page.route('**/rest/v1/rpc/registro_actividad_fn', async (route) => {
    const pedido = route.request().postDataJSON(); estado.registros.push(pedido)
    if (estado.registroRevocado) return route.fulfill({ status: 403, json: { code: '42501', message: 'Registro revocado' } })
    const items = pedido.p_analista_ids && !pedido.p_analista_ids.includes(analista.analista_id) ? [] : [{
      id: '11111111-2222-4333-8444-555555555555', lead_id: cliente.id, lead_nombre: cliente.nombre_completo,
      lead_etapa: 'nuevo', etapa_en_ese_momento: 'nuevo', tipo: 'llamada_realizada', detalle: `Llamada ficticia F5 del ${pedido.p_desde}`,
      metadata: { resultado: 'interesado' }, creado_por: analista.analista_id, autor_nombre: analista.nombre_completo,
      creado_en: `${pedido.p_desde}T15:00:00.000Z`,
    }]
    const paginas = estado.paginado && items[0] ? Array.from({ length: 26 }, (_, i) => ({ ...items[0],
      id: `11111111-2222-4333-8444-${String(i + 1).padStart(12, '0')}`,
      detalle: `${items[0]!.detalle} · gestión ${i + 1}`, creado_en: `${pedido.p_desde}T15:${String(25 - i).padStart(2, '0')}:00.000Z`,
    })) : items
    return route.fulfill({ json: { version: 1, zona: 'America/Lima', desde: pedido.p_desde, hasta: pedido.p_hasta,
      generado_en: fixture.pulso.generado_en, limite: pedido.p_limite, items: pedido.p_antes_de ? paginas.slice(25) : paginas } })
  })
  await loginReal(page)
  await page.getByRole('button', { name: 'Gestión Diaria', exact: true }).click()
  await page.getByRole('button', { name: 'Ocultar menú', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Resumen por supervisor' })).toBeVisible()
  return estado
}

test('F6 horizontal: gerencia conserva tabla y detalle con el menú abierto en un portátil', async ({ page, browser, baseURL }, info) => {
  const referencia = await browser.newPage({ baseURL, viewport: { width: 1366, height: 900 } })
  await referencia.clock.setFixedTime(new Date('2026-09-24T15:00:00Z'))
  await montarBackendReal(referencia, { rolCrm: 'supervisor', leads: [], tareas: [] })
  await referencia.route('**/rest/v1/rpc/gestion_diaria_equipo_fn', route => route.fulfill({ json: {
    ...diaEquipoPrueba(Array.from({ length: 10 }, (_, i) => filaEquipoPrueba({
      analista_id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`, nombre_completo: `ANALISTA ${i + 1}`,
    }))), dia: '2026-09-24', supervisor_id: UID,
  } }))
  await loginReal(referencia)
  await referencia.getByRole('button', { name: 'Gestión Diaria', exact: true }).click()
  await expect(referencia.getByRole('group', { name: 'Resumen del equipo' })).toBeVisible()
  await referencia.screenshot({ path: info.outputPath('supervision-1366-menu-abierto.png'), fullPage: true })
  await referencia.close()

  await montar(page)
  await page.getByRole('button', { name: 'Fijar menú abierto', exact: true }).click()
  await page.mouse.move(1000, 80)
  for (const [width, height] of [[1366, 900], [1366, 768], [1280, 800]]) {
    await page.setViewportSize({ width: width!, height: height! })
    await page.screenshot({ path: info.outputPath(`gerencia-${width}x${height}-menu-abierto.png`), fullPage: true })
    const panel = page.getByRole('region', { name: 'Detalle de la operación', exact: true })
    await expect(panel).toBeVisible()
    const tabla = await page.getByRole('region', { name: 'Equipos de la operación', exact: true }).boundingBox()
    const lateral = await panel.boundingBox()
    expect(lateral!.x).toBeGreaterThanOrEqual(tabla!.x + tabla!.width)
    expect(Math.abs(lateral!.y - tabla!.y)).toBeLessThan(2)
    expect(tabla!.y).toBeLessThan(350)
    const indicadores = page.getByRole('region', { name: 'Indicadores de la operación' })
    const posiciones = await indicadores.locator('dl>div').evaluateAll(nodos => nodos.map(n => n.getBoundingClientRect().y))
    expect(new Set(posiciones).size).toBe(1)
    expect(await page.locator('[data-vista-scroll="gestion-diaria"]').evaluate(n => n.scrollHeight <= n.clientHeight + 1 && n.scrollWidth <= n.clientWidth + 1)).toBe(true)
  }
  const columnas = page.getByRole('region', { name: 'Desplazar tabla de equipos', exact: true })
  await columnas.focus(); await columnas.press('ArrowRight')
  await expect.poll(() => columnas.evaluate(n => n.scrollLeft)).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Ordenar equipos por dispersión de contacto', exact: true }).focus()
  await expect(page.getByRole('link', { name: grupo.nombre, exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Comparar días', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Cifras del día, anterior y referencia' }).getByRole('row')).toHaveCount(9)
  await page.screenshot({ path: info.outputPath('gerencia-comparacion.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Comparar días', exact: true })).toBeFocused()
  await page.getByRole('link', { name: grupo.nombre, exact: true }).click()
  await page.getByRole('button', { name: `Seleccionar a ${analista.nombre_completo}`, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Detalle de la operación', exact: true })).toContainText(analista.nombre_completo!)
  expect(await page.getByRole('table', { name: 'Actividad y pendientes por analista' }).locator('tbody tr').first().evaluate(n => getComputedStyle(n).display)).toBe('table-row')
  await page.screenshot({ path: info.outputPath('gerencia-analista-horizontal.png'), fullPage: true })
  await page.getByRole('tab', { name: 'Hábitos del equipo', exact: true }).click()
  await page.getByRole('button', { name: `Ver hábitos de ${analista.nombre_completo}`, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const habitos = await page.getByRole('region', { name: 'Comparación de hábitos', exact: true }).boundingBox()
  const detalleHabitos = await page.getByRole('region', { name: 'Detalle de hábitos', exact: true }).boundingBox()
  expect(detalleHabitos!.x).toBeGreaterThanOrEqual(habitos!.x + habitos!.width)
  await page.screenshot({ path: info.outputPath('gerencia-habitos-horizontal.png'), fullPage: true })
})

test('F5 escritorio: operación, equipo, analista, registro, ficha y vuelta con contexto', async ({ page }, info) => {
  const estado = await montar(page)
  const vista = page.getByRole('region', { name: 'Toda la operación', exact: true })
  await expect(vista).toContainText('1008 tareas vencidas en total')
  await expect(vista).toContainText('Promedio: 7 de 7 días con actividad')
  await page.screenshot({ path: info.outputPath('f5-operacion-escritorio.png'), fullPage: true })
  const enlaceEquipo = vista.getByRole('link', { name: grupo.nombre, exact: true })
  await enlaceEquipo.focus()
  await enlaceEquipo.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/gestion-diaria/equipo/${grupo.clave}$`))
  const detalle = vista.getByRole('region', { name: 'Detalle de la operación' })
  await expect(vista.getByRole('region', { name: 'Analistas del equipo' }).getByRole('heading', { name: grupo.nombre, exact: true })).toBeFocused()
  await detalle.getByRole('heading', { name: grupo.nombre, exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('f5-equipo-escritorio.png'), fullPage: true })
  await page.getByRole('searchbox', { name: 'Buscar analista del equipo' }).fill(analista.nombre_completo!)
  const fila = page.getByRole('button', { name: `Seleccionar a ${analista.nombre_completo}`, exact: true })
  await fila.click()
  await expect(page).toHaveURL(new RegExp(`/gestion-diaria/analista/${analista.analista_id}$`))
  await expect(fila).toBeFocused()
  await page.getByRole('button', { name: `Ir al detalle de ${analista.nombre_completo}`, exact: true }).click()
  await expect(detalle.getByRole('heading', { name: analista.nombre_completo!, exact: true })).toBeFocused()
  await detalle.getByRole('tab', { name: 'Registro', exact: true }).click()
  await expect(detalle).toContainText(`Llamada ficticia F5 del ${DIA}`)
  expect(estado.registros.some((r) => r.p_desde === DIA && JSON.stringify(r.p_analista_ids) === JSON.stringify([analista.analista_id]))).toBe(true)
  await detalle.getByRole('button', { name: cliente.nombre_completo, exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/analista/${analista.analista_id}/lead/${cliente.id}$`))
  await expect(page.getByRole('heading', { name: cliente.nombre_completo, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ficha', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/analista/${analista.analista_id}$`))
  await expect(page.getByLabel('Día de la operación', { exact: true })).toHaveValue(DIA)
  await expect(detalle).toContainText(`Llamada ficticia F5 del ${DIA}`)
  await expect(page.getByRole('searchbox', { name: 'Buscar analista del equipo' })).toHaveValue(analista.nombre_completo!)
  await page.goBack()
  await expect(page.getByRole('heading', { name: cliente.nombre_completo, exact: true })).toBeVisible()
  await page.goForward()
  await expect(detalle).toBeVisible()
  await page.screenshot({ path: info.outputPath('f5-analista-escritorio.png'), fullPage: true })
})

test('F5 móvil: fecha, recarga y enlace directo sin desbordamiento', async ({ page }, info) => {
  const estado = await montar(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.mouse.move(380, 80)
  const dia = page.getByLabel('Día de la operación', { exact: true })
  await dia.fill('2026-09-22')
  await dia.press('Enter')
  await expect(page.getByRole('region', { name: 'Indicadores de la operación' })).toContainText('2026-09-21 completo')
  await expect.poll(() => estado.dias.at(-1)).toBe('2026-09-22')
  await page.getByRole('link', { name: grupo.nombre, exact: true }).click()
  await page.reload()
  // Los portales se alojan fuera del workspace; esperar también su salida del splash.
  await expect.poll(() => page.locator('main').evaluate((n) => n.closest('[inert]') === null)).toBe(true)
  await expect(page).toHaveURL(new RegExp(`/equipo/${grupo.clave}$`))
  const detalle = page.getByRole('region', { name: 'Detalle de la operación' })
  await expect(detalle).toBeVisible()
  await expect(page.getByRole('dialog', { name: grupo.nombre, exact: true })).toBeVisible()
  await detalle.getByRole('button', { name: 'Cerrar detalle', exact: true }).click()
  await expect(dia).toHaveValue('2026-09-22')
  await dia.fill('2026-09-21')
  await dia.press('Enter')
  await expect.poll(() => estado.dias.at(-1)).toBe('2026-09-21')
  await expect(dia).toBeFocused()
  await page.getByRole('button', { name: 'Ver detalle', exact: true }).click()
  await expect(detalle).toContainText(grupo.nombre)
  await detalle.getByRole('heading', { name: grupo.nombre, exact: true }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('f5-equipo-movil.png'), fullPage: true })
  await detalle.getByRole('button', { name: 'Cerrar detalle', exact: true }).click()
  await page.getByRole('button', { name: `Seleccionar a ${analista.nombre_completo}`, exact: true }).click()
  await detalle.getByRole('link', { name: grupo.nombre, exact: true }).click()
  await expect(page.getByRole('region', { name: 'Analistas del equipo' }).getByRole('heading', { name: grupo.nombre, exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Ver detalle', exact: true }).click()
  await page.getByRole('region', { name: 'Detalle de la operación' }).getByRole('link', { name: 'Toda la operación', exact: true }).click()
  await expect(page).toHaveURL(/#\/gestion-diaria$/)
  await expect(page.getByRole('heading', { name: 'Equipos y atención actual', exact: true })).toBeFocused()
  await page.getByRole('heading', { name: 'Toda la operación', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('f5-operacion-movil.png'), fullPage: true })
})

test('F5 hábitos: períodos reales de 7/14/30, hueco, comparación y cortes sin activar umbral', async ({ page }, info) => {
  const estado = await montar(page)
  await page.getByRole('tab', { name: 'Hábitos del equipo', exact: true }).click()
  const informe = page.getByRole('region', { name: 'Reporte de hábitos', exact: true })
  await expect(informe).toContainText('14 días calendario')
  await page.getByLabel(`Período hasta ${DIA}`, { exact: true }).selectOption('7')
  await expect(informe).toContainText('7 días calendario')
  await informe.getByRole('button', { name: `Ver hábitos de ${analista.nombre_completo}`, exact: true }).click()
  await informe.getByText(`Ver días de ${analista.nombre_completo}`, { exact: true }).click()
  await expect(informe.getByRole('table', { name: `Hábitos diarios de ${analista.nombre_completo}` })).toContainText('165 min')
  await informe.getByRole('button', { name: 'Cómo leer los hábitos', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('La alerta de tasa muy baja sigue apagada')
  await page.getByRole('button', { name: 'Cerrar explicación', exact: true }).click()
  await page.screenshot({ path: info.outputPath('f5-habitos.png'), fullPage: true })
  await informe.getByRole('table', { name: `Hábitos diarios de ${analista.nombre_completo}` }).getByRole('row', { name: new RegExp(DIA) }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('f5-habitos-hueco.png'), fullPage: true })
  await page.getByLabel(`Período hasta ${DIA}`, { exact: true }).selectOption('30')
  await expect(informe).toContainText('30 días calendario')
  expect(estado.periodos).toEqual(expect.arrayContaining([7, 14, 30]))
  await informe.getByRole('button', { name: `Ver hábitos de ${analista.nombre_completo}`, exact: true }).click()
  await informe.getByRole('link', { name: 'Ver pulso y registro', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Detalle de la operación' })).toContainText(analista.nombre_completo!)
})

test('F5 error y revocación ocultan datos; recuperación vuelve a consultar', async ({ page }) => {
  const estado = await montar(page)
  estado.error = true
  await page.getByRole('button', { name: 'Actualizar operación', exact: true }).click()
  const alerta = page.getByRole('region', { name: 'Toda la operación' }).getByRole('alert')
  await expect(alerta).toContainText('datos anteriores se han ocultado')
  await expect(page.getByRole('table', { name: 'Resumen por supervisor' })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Registro general de la operación' })).toHaveCount(0)
  estado.error = false
  await alerta.getByRole('button', { name: 'Reintentar', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Resumen por supervisor' })).toBeVisible()
  estado.revocado = true
  await page.getByRole('button', { name: 'Actualizar operación', exact: true }).click()
  await expect(alerta).toContainText('ya no tiene permiso')
  await expect(page.getByRole('table')).toHaveCount(0)
})

test('F5 conserva la fila fuera de equipos y exportación del registro cargado', async ({ page }) => {
  await montar(page)
  await page.getByRole('link', { name: 'Fuera de equipos comerciales', exact: true }).click()
  const detalle = page.getByRole('region', { name: 'Detalle de la operación' })
  await expect(page.getByRole('region', { name: 'Analistas del equipo' })).toContainText('Sin autor: 1 llamadas')
  await expect(detalle).toContainText('Los registros sin autor se consultan en el registro general')
  await page.getByRole('button', { name: 'Registro general', exact: true }).click()
  const general = page.getByRole('region', { name: 'Registro general de la operación' })
  await expect(general).toContainText(`Llamada ficticia F5 del ${DIA}`)
  const descarga = page.waitForEvent('download')
  await general.getByRole('button', { name: /Exportar/ }).click()
  expect((await descarga).suggestedFilename()).toContain(DIA)
})

test('F6 gerencia: densidad, filtros y registro permanecen al ampliar, redimensionar y volver', async ({ page }, info) => {
  const estado = await montar(page)
  estado.paginado = true
  const vista = page.getByRole('region', { name: 'Toda la operación', exact: true })
  const indicadores = vista.getByRole('region', { name: 'Indicadores de la operación' }).locator('dl')
  const cifras = await indicadores.textContent()
  await expect(vista).toHaveAttribute('data-estrecho', 'false')
  expect(await page.locator('[data-vista-scroll="gestion-diaria"]').evaluate((n) => n.scrollHeight <= n.clientHeight + 1)).toBe(true)
  const equipos = page.getByRole('table', { name: 'Resumen por supervisor' })
  const ultimaFila = await equipos.locator('tbody tr').last().boundingBox()
  const tabla = await equipos.locator('..').boundingBox()
  expect(ultimaFila!.y + ultimaFila!.height).toBeLessThanOrEqual(tabla!.y + tabla!.height + 1)
  await page.getByRole('searchbox', { name: 'Buscar equipo', exact: true }).fill(grupo.nombre)
  await expect(equipos.locator('tbody tr')).toHaveCount(1)
  await expect(indicadores).toHaveText(cifras!)
  await page.getByRole('link', { name: grupo.nombre, exact: true }).click()
  const buscar = page.getByRole('searchbox', { name: 'Buscar analista del equipo', exact: true })
  await buscar.fill(analista.nombre_completo!)
  const seleccionar = page.getByRole('button', { name: `Seleccionar a ${analista.nombre_completo}`, exact: true })
  await seleccionar.click()
  const panel = page.getByRole('region', { name: 'Detalle de la operación', exact: true })
  await panel.getByRole('tab', { name: 'Registro', exact: true }).click()
  const etapa = panel.getByRole('combobox', { name: 'Etapa actual del lead', exact: true })
  await etapa.selectOption('nuevo')
  await expect(panel).toContainText(`Llamada ficticia F5 del ${DIA}`)
  await expect(panel.getByRole('listitem')).toHaveCount(25)
  await panel.getByRole('button', { name: 'Ver más', exact: true }).click()
  await expect(panel.getByRole('listitem')).toHaveCount(26)
  await panel.getByRole('button', { name: 'Ampliar panel', exact: true }).click()
  await expect(page.getByRole('dialog', { name: analista.nombre_completo!, exact: true })).toBeVisible()
  await expect(etapa).toHaveValue('nuevo')
  await expect(panel.getByRole('listitem')).toHaveCount(26)
  await panel.getByRole('button', { name: cliente.nombre_completo, exact: true }).first().click()
  await expect(page.getByRole('heading', { name: cliente.nombre_completo, exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('heading', { name: cliente.nombre_completo, exact: true })).toHaveCount(0)
  await expect(page.getByRole('dialog', { name: analista.nombre_completo!, exact: true })).toBeVisible()
  await expect(panel.getByRole('listitem')).toHaveCount(26)
  await page.screenshot({ path: info.outputPath('f6-registro-ampliado.png'), fullPage: true })
  await panel.getByRole('button', { name: 'Restaurar panel', exact: true }).click()
  await page.setViewportSize({ width: 1000, height: 900 })
  await expect(page.getByRole('dialog', { name: analista.nombre_completo!, exact: true })).toBeVisible()
  await expect(etapa).toHaveValue('nuevo')
  await expect(panel.getByRole('listitem')).toHaveCount(26)
  await page.setViewportSize({ width: 1512, height: 900 })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(etapa).toHaveValue('nuevo')
  await page.getByRole('button', { name: 'Registro general', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Registro general de la operación' })).toBeVisible()
  await panel.getByRole('button', { name: 'Cerrar detalle', exact: true }).click()
  await expect(etapa).toHaveValue('nuevo')
  await expect(buscar).toHaveValue(analista.nombre_completo!)
  await panel.getByRole('button', { name: 'Cerrar detalle', exact: true }).click()
  await expect(seleccionar).toBeFocused()
  await page.getByRole('region', { name: 'Analistas del equipo', exact: true }).getByRole('link', { name: 'Toda la operación', exact: true }).click()
  await expect(page.getByRole('searchbox', { name: 'Buscar equipo', exact: true })).toHaveValue(grupo.nombre)
})

test('F6 hábitos: búsqueda, selección por teclado y móvil conservan el día abierto', async ({ page }, info) => {
  await montar(page)
  await page.getByRole('tab', { name: 'Hábitos del equipo', exact: true }).click()
  const buscar = page.getByRole('searchbox', { name: 'Buscar analista en hábitos', exact: true })
  await buscar.fill(analista.nombre_completo!)
  const seleccion = page.getByRole('button', { name: `Ver hábitos de ${analista.nombre_completo}`, exact: true })
  await seleccion.focus(); await seleccion.press('Enter')
  await expect(seleccion).toBeFocused()
  await page.getByRole('button', { name: `Ir al detalle de hábitos de ${analista.nombre_completo}` }).click()
  const panel = page.getByRole('region', { name: 'Detalle de hábitos', exact: true })
  await expect(panel.getByRole('heading', { name: analista.nombre_completo!, exact: true })).toBeFocused()
  await panel.getByText(`Ver días de ${analista.nombre_completo}`, { exact: true }).click()
  await expect(panel.locator('details')).toHaveAttribute('open', '')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('dialog', { name: analista.nombre_completo!, exact: true })).toBeVisible()
  await expect(panel.locator('details')).toHaveAttribute('open', '')
  expect(await panel.evaluate((n) => n.scrollWidth <= n.clientWidth)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('f6-habitos-movil.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(seleccion).toBeFocused()
  await expect(buscar).toHaveValue(analista.nombre_completo!)
  await buscar.focus()
  await seleccion.click()
  await panel.getByRole('button', { name: 'Cerrar detalle', exact: true }).click()
  await expect(seleccion).toBeFocused()
  await buscar.fill('NO EXISTE')
  await expect(page.getByRole('table', { name: 'Comparación de hábitos por analista' })).toContainText('Ningún analista coincide')
})

for (const ambito of ['general', 'analista']) test(`F6 una revocación del registro ${ambito} oculta Pulso y Hábitos hasta verificar la sesión`, async ({ page }) => {
  const estado = await montar(page)
  if (ambito === 'general') await page.getByRole('button', { name: 'Registro general', exact: true }).click()
  else {
    await page.getByRole('link', { name: grupo.nombre, exact: true }).click()
    await page.getByRole('button', { name: `Seleccionar a ${analista.nombre_completo}`, exact: true }).click()
    await page.getByRole('tab', { name: 'Registro', exact: true }).click()
  }
  const registro = page.getByRole('region', { name: `Registro de actividad del ${DIA}`, exact: true })
  await expect(registro).toContainText(`Llamada ficticia F5 del ${DIA}`)
  estado.registroRevocado = true
  await registro.getByRole('button', { name: 'Actualizar', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Toda la operación', exact: true }).getByRole('alert')).toContainText('ya no tiene permiso')
  await expect(page.getByRole('table')).toHaveCount(0)
  await expect(registro).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Verificar sesión', exact: true })).toBeFocused()
  await page.getByRole('tab', { name: 'Hábitos del equipo', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Verificar sesión', exact: true })).toBeVisible()
  await expect(page.getByRole('table')).toHaveCount(0)
  estado.registroRevocado = false
  await page.getByRole('button', { name: 'Verificar sesión', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Resumen por supervisor' })).toBeVisible()
})

test('F6 al ampliar desde móvil aparece el equipo seleccionado y su detalle', async ({ page }) => {
  await montar(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: grupo.nombre, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.setViewportSize({ width: 1512, height: 900 })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Detalle de la operación' }).getByRole('heading', { name: grupo.nombre, exact: true })).toBeVisible()
})
