import { expect, test } from '@playwright/test'
import { bloquearSupabase, entrarDemo, loginReal, montarBackendReal, rankingAgostoReal } from './_helpers'
import { irAModulo } from './_navegacion'

test.use({ viewport: { width: 390, height: 844 }, hasTouch: true })

test('Pendientes: Resumen y campana comparten total, tarjetas abren el caso y la bandeja conserva consulta al regresar', async ({ page }, info) => {
  await page.clock.setFixedTime(new Date('2026-08-25T15:00:00Z'))
  const datos = rankingAgostoReal()
  const metasBase = (datos.configuracionMetas.vendedores as Array<Record<string, unknown>>)[0]!
  const cumplimientoBase = (datos.cumplimientoMetas.vendedores as Array<Record<string, unknown>>)[0]!
  const personas = [15, 30, 17, 35].map((objetivo, i) => ({ vendedor_id: `84000000-0000-4000-8000-00000000010${i}`, nombre: `ANALISTA PRUEBA ${i + 1}`, conversion_objetivo: objetivo }))
  datos.configuracionMetas.vendedores = personas.map(p => ({ ...metasBase, ...p }))
  datos.cumplimientoMetas.vendedores = personas.map(p => ({ ...cumplimientoBase, ...p }))
  await montarBackendReal(page, { configuracionMetas: datos.configuracionMetas, cumplimientoMetas: datos.cumplimientoMetas, metricas: { conversionMensual: datos.conversionMensual } })
  await loginReal(page, { esperarWorkspace: false })
  const pendientes = page.getByRole('region', { name: 'Pendientes de gestión' })
  await expect(pendientes).toBeVisible()
  await expect(pendientes).not.toHaveAttribute('aria-busy', 'true')
  const abrirTodos = pendientes.getByRole('link', { name: /Ver todos/ })
  await expect(abrirTodos).toHaveText(/\(4\)/)
  await expect(page.locator('header').getByRole('link', { name: /pendientes/ })).toContainText('4')
  await expect(pendientes.getByRole('listitem')).toHaveCount(3)
  const responsables = await pendientes.locator('li small').allTextContents()
  await abrirTodos.click()
  await expect(page.getByRole('heading', { name: 'Señales de gestión' })).toBeVisible()
  const activas = page.getByRole('list', { name: 'Pendientes activos' })
  await expect(activas.getByRole('listitem')).toHaveCount(4)
  expect(await activas.locator('li p').filter({ hasText: 'Responsable:' }).allTextContents()).toEqual([...responsables, 'Responsable: ANALISTA PRUEBA 3'])
    await page.getByRole('button', { name: 'Filtrar', exact: true }).click()
    await page.getByRole('searchbox', { name: 'Buscar pendiente' }).fill('ZZZ sin coincidencias')
    await expect(page.getByText('Sin coincidencias', { exact: true })).toBeVisible()
    await irAModulo(page, 'Gestión Diaria')
    await page.goBack()
    await expect(page.getByRole('searchbox', { name: 'Buscar pendiente' })).toHaveValue('ZZZ sin coincidencias')
    await page.getByRole('button', { name: 'Limpiar', exact: true }).click()
    const enlace = activas.getByRole('link').first()
    const destino = await enlace.getAttribute('href')
    await enlace.click()
    await expect(page).toHaveURL(new RegExp(destino!.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '$'))
    await page.goBack()
    await expect(enlace).toBeFocused()
  await page.screenshot({ path: info.outputPath('pendientes-movil.png') })
})

test('Citas: equipo y período visibles, filtros plegables conservan consulta y detalle', async ({ page }) => {
  await bloquearSupabase(page)
  await entrarDemo(page, 'Gerencia')
  await irAModulo(page, 'Citas')
  await expect(page.getByRole('heading', { name: 'Citas del equipo' })).toBeVisible()
  await expect(page.getByLabel('Mes', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: /^Filtrar/ }).click()
  await page.getByLabel('Semana', { exact: true }).selectOption('2')
  await page.getByRole('button', { name: /^Filtrar/ }).click()
  await expect(page.getByLabel('Semana', { exact: true })).toBeHidden()
  await page.getByRole('tab', { name: 'Agenda', exact: true }).click()
  await page.getByRole('button', { name: /^Filtrar/ }).click()
  await expect(page.getByLabel('Semana', { exact: true })).toHaveValue('2')
  await irAModulo(page, 'Gestión Diaria')
  await page.goBack()
  await page.getByRole('button', { name: /^Filtrar/ }).click()
  await expect(page.getByLabel('Semana', { exact: true })).toHaveValue('2')
  const mesGuardado = await page.getByLabel('Mes', { exact: true }).inputValue()
  await page.getByLabel('Mes', { exact: true }).fill('')
  await irAModulo(page, 'Gestión Diaria')
  await page.goBack()
  await expect(page.locator('#citas-consulta-campos').getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('Mes', { exact: true })).toBeVisible()
  await page.getByLabel('Mes', { exact: true }).fill(mesGuardado)
  await page.setViewportSize({ width: 1024, height: 900 })
  await expect(page.getByLabel('Semana', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Semana', { exact: true })).toHaveValue('2')
})

test('Gestión Diaria: ordenar equipos y abrir cifras a 360 px', async ({ page }, info) => {
  await bloquearSupabase(page)
  await page.setViewportSize({ width: 360, height: 800 })
  await entrarDemo(page, 'Gerencia')
  await irAModulo(page, 'Gestión Diaria')
  await page.getByRole('combobox', { name: 'Ordenar equipos', exact: true }).selectOption('llamadas')
  await expect(page.getByRole('button', { name: 'Ordenar equipos por llamadas' })).toBeHidden()
  await page.getByRole('button', { name: /Cambiar a orden ascendente/ }).click()
  await expect(page.getByRole('button', { name: /Cambiar a orden descendente/ })).toBeVisible()
  await page.getByRole('button', { name: /Seleccionar Equipo de SUPERVISOR UNO/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: /Seleccionar Equipo de SUPERVISOR UNO/ })).toBeFocused()
  await page.screenshot({ path: info.outputPath('gestion-diaria-360.png') })
})

test('Red: aviso de desconexión en cualquier módulo, recuperación sin perder el período histórico', async ({ page, context }) => {
  await page.clock.setFixedTime(new Date('2026-10-05T15:00:00Z'))
  await montarBackendReal(page)
  await loginReal(page, { esperarWorkspace: false })
  await irAModulo(page, 'Metas y cumplimiento')
  await page.getByLabel('Mes calendario').fill('2026-08')
  await expect(page.getByLabel('Mes calendario')).toHaveValue('2026-08')
  await context.setOffline(true)
  await expect(page.locator('.crm-conexion')).toContainText('Sin conexión')
  await context.setOffline(false)
  await expect(page.locator('.crm-conexion')).toHaveCount(0)
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByLabel('Mes calendario')).toHaveValue('2026-08')
})

test('Actualización: se aplaza, respeta Más y sólo actualiza por decisión de la persona', async ({ page }, info) => {
  await bloquearSupabase(page)
  await entrarDemo(page, 'Gerencia')
  await page.evaluate(async (ruta) => {
    const { montarAvisoVersion } = await import(ruta)
    montarAvisoVersion()
  }, '/e2e/_aviso-version.tsx')
  const aviso = page.getByRole('status', { name: 'Nueva versión del CRM disponible' })
  const host = page.locator('[data-aviso-version-prueba]')
  await expect(aviso).toBeVisible()
  await expect(host).not.toHaveAttribute('data-actualizacion-solicitada', 'true')
  const cajaAviso = await aviso.boundingBox()
  const cajaBarra = await page.locator('.gm-barra').boundingBox()
  expect(cajaAviso!.y + cajaAviso!.height).toBeLessThanOrEqual(cajaBarra!.y)
  await page.getByRole('button', { name: 'Más', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(aviso).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(aviso).toBeVisible()
  await aviso.getByRole('button', { name: 'Más tarde' }).click()
  await expect(aviso.getByRole('button', { name: 'Ver actualización disponible' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('actualizacion-aplazada.png') })
  await aviso.getByRole('button', { name: 'Ver actualización disponible' }).click()
  await aviso.getByRole('button', { name: 'Ya guardé, actualizar' }).click()
  await expect(host).toHaveAttribute('data-actualizacion-solicitada', 'true')
})

for (const width of [360, 430, 767, 768]) test(`Pantallas prioritarias: lectura y controles a ${width}px`, async ({ page }, info) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width, height: 900 })
  await bloquearSupabase(page)
  await entrarDemo(page, 'Gerencia')
  for (const nombre of ['Gestión Diaria', 'Citas', 'Ranking', 'Metas y cumplimiento', 'Facturación', 'Cartera']) await test.step(nombre, async () => {
    await irAModulo(page, nombre)
    await expect(page.locator('main h1').first()).toBeVisible()
    await expect(page.getByText('Algo salió mal en esta sección')).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const area = page.locator('[data-vista-scroll]')
    await expect(area).toBeVisible()
    await expect(area.getByRole('heading').first()).toBeVisible()
    expect(await area.evaluate(e => e.scrollWidth <= e.clientWidth + 1)).toBe(true)
    if (width === 360) await page.screenshot({ path: info.outputPath(`${nombre.replaceAll(' ', '-')}-360.png`) })
  })
})
