import { expect, test } from '@playwright/test'
import { bloquearSupabase, entrarDemo, loginReal, montarBackendReal, rankingAgostoReal } from './_helpers'
import { montarConsultaCitas } from './_citas'

test.use({ viewport: { width: 390, height: 844 }, hasTouch: true })

test('Resumen móvil: total por equipo coincide con Citas y conserva día/equipo al recargar', async ({ page }, info) => {
  await page.clock.setFixedTime(new Date('2026-08-04T15:00:00Z'))
  const foto = rankingAgostoReal()
  await montarBackendReal(page, { configuracionMetas: foto.configuracionMetas, cumplimientoMetas: foto.cumplimientoMetas, metricas: { conversionMensual: foto.conversionMensual } })
  await montarConsultaCitas(page, 'pendiente')
  await loginReal(page, { esperarWorkspace: false })
  const resumen = page.getByTestId('resumen-gerencia-movil')
  await expect(resumen).toBeVisible()
  await expect(resumen.getByRole('heading', { name: 'Bienvenido, Gerente' })).toBeVisible()
  await expect(resumen.getByRole('button', { name: /Capital confirmado/ })).toContainText('S/ 65,295')
  let fallaCapital = true
  await page.route('**/rest/v1/rpc/cumplimiento_metas_fn', route => fallaCapital
    ? route.fulfill({ status: 500, json: { message: 'Fallo temporal de prueba' } }) : route.fallback())
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  const errorCapital = resumen.getByRole('alert').filter({ hasText: 'No se pudieron actualizar el capital y la meta del mes.' })
  await expect(errorCapital).toBeVisible()
  await expect(resumen.getByRole('button', { name: /Capital confirmado/ })).not.toContainText('S/ 65,295')
  await expect(resumen).not.toContainText('Se muestran los últimos datos')
  fallaCapital = false
  await errorCapital.getByRole('button', { name: 'Reintentar' }).click()
  await expect(resumen.getByRole('button', { name: /Capital confirmado/ })).toContainText('S/ 65,295')
  await expect(resumen.getByRole('link', { name: /Citas de hoy/ })).toContainText('1')
  await expect(resumen.getByRole('button', { name: /Solicitudes/ })).toContainText('0')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('resumen-movil-crm.png'), fullPage: true })
  await resumen.getByRole('link', { name: 'Equipo de SUPERVISOR DE PRUEBA: 1 cita de hoy. Ir a Citas' }).click()
  await expect(page).toHaveURL(/#\/reuniones\/dia\/2026-08-04\/equipo\/84000000-0000-4000-8000-000000000030$/)
  await expect(page.getByTestId('conteo-citas')).toContainText('1 citas de tu consulta')
  await expect(page.getByRole('tab', { name: 'Agenda', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.reload()
  await expect(page.getByTestId('conteo-citas')).toContainText('1 citas de tu consulta')
  await expect(page.getByLabel('Supervisor', { exact: true })).toHaveValue('84000000-0000-4000-8000-000000000030')
  await page.getByRole('button', { name: /Quitar Día:/ }).click()
  await expect(page.getByTestId('conteo-citas')).toContainText('4 citas de tu consulta')
  await expect(page).toHaveURL(/#\/reuniones\/mes\/2026-08\/equipo\/84000000-0000-4000-8000-000000000030$/)
  await page.reload()
  await expect(page.getByTestId('conteo-citas')).toContainText('4 citas de tu consulta')
  await page.goBack()
  await expect(resumen).toBeVisible()
  await resumen.getByRole('button', { name: /Meta de capital/ }).click()
  await expect(page).toHaveURL(/#\/metas$/)
  await expect(page.getByRole('heading', { name: 'Metas mensuales' })).toBeVisible()
})

test('Resumen móvil: un fallo de Citas no se convierte en cero y permite recuperarse', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-04T15:00:00Z'))
  await montarBackendReal(page)
  await page.route('**/rest/v1/rpc/citas_gerencia_consulta_fn', route => route.fulfill({ status: 500, json: { message: 'Fallo de prueba' } }))
  await loginReal(page, { esperarWorkspace: false })
  const resumen = page.getByTestId('resumen-gerencia-movil')
  await expect(resumen.getByRole('link', { name: /Citas de hoy/ })).toContainText('—')
  const error = resumen.getByRole('alert').filter({ hasText: 'No se pudieron actualizar las citas.' })
  await expect(error).toBeVisible()
  await montarConsultaCitas(page, 'pendiente')
  await error.getByRole('button', { name: 'Reintentar' }).click()
  await expect(resumen.getByRole('link', { name: /Citas de hoy/ })).toContainText('1')
})

test('Resumen compacto solo en móvil: acceso al completo, escritorio', async ({ page }) => {
  const solicitudes = await bloquearSupabase(page)
  await entrarDemo(page, 'Gerencia')
  const resumen = page.getByTestId('resumen-gerencia-movil')
  await expect(resumen).toBeVisible()
  await resumen.getByRole('button', { name: 'Abrir el resumen completo' }).click()
  await expect(resumen).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Volver al resumen compacto' })).toBeFocused()
  await page.getByRole('button', { name: 'Volver al resumen compacto' }).click()
  await expect(resumen).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Bienvenido, Gerencia' })).toBeFocused()
  await page.setViewportSize({ width: 430, height: 932 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(resumen).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Resultados por semana de ingreso' })).toBeVisible()
  expect(solicitudes()).toBe(0)
})
