import * as v from 'valibot'
import { ESTADOS_TAREA, TIPOS_TAREA, MODALIDADES_REUNION_TODAS, RESULTADOS_REUNION_TODOS, MOTIVOS_NO_REALIZADA_TODOS } from './tipos'

export const TareaRowSchema = v.object({
  id: v.string(),
  lead_id: v.nullable(v.string()),
  perfil_id: v.nullable(v.string()),
  inversionista_id: v.optional(v.nullable(v.string())),
  inversionista_canonico_id: v.optional(v.nullable(v.string())),
  postventa_perfil_ids: v.optional(v.array(v.pipe(v.string(), v.uuid()))),
  postventa_revision: v.optional(v.nullable(v.pipe(v.number(), v.integer(), v.minValue(1)))),
  vendedor_id: v.nullable(v.string()),
  asignado_supervisor_id: v.nullable(v.string()),
  tipo: v.picklist(TIPOS_TAREA.map((t) => t.k)),
  titulo: v.string(),
  nota: v.nullable(v.string()),
  vence_en: v.string(),
  duracion_min: v.nullable(v.number()),
  estado: v.picklist(ESTADOS_TAREA),
  modalidad_reunion: v.nullable(v.picklist(MODALIDADES_REUNION_TODAS)),
  ubicacion_reunion: v.nullable(v.string()),
  enlace_reunion: v.nullable(v.string()),
  resultado_reunion: v.nullable(v.picklist(RESULTADOS_REUNION_TODOS)),
  motivo_no_realizada: v.nullable(v.picklist(MOTIVOS_NO_REALIZADA_TODOS)),
  detalle_cierre_reunion: v.nullable(v.string()),
  confirmada_en: v.nullable(v.string()),
  reagendada_de: v.nullable(v.string()),
  reprogramaciones: v.number(),
  activo: v.boolean(),
  creado_en: v.string(),
  /** Embebidos por crm.tareas_pendientes_fn (Fase 2 «sin topes»); nulos si el lead no es visible. */
  lead_nombre: v.optional(v.nullable(v.string())),
  lead_etapa: v.optional(v.nullable(v.string())),
  /** Fase 4b «sin topes» (20260920045202): teléfono, capital y tenencia del lead; opcionales por si el servidor aún no los manda. */
  lead_telefono: v.optional(v.nullable(v.string())),
  lead_monto_estimado: v.optional(v.nullable(v.union([v.number(), v.string()]))),
  lead_moneda: v.optional(v.nullable(v.string())),
  lead_vendedor_id: v.optional(v.nullable(v.string())),
  lead_supervisor_id: v.optional(v.nullable(v.string())),
  lead_correo: v.optional(v.nullable(v.string())),
  lead_no_contactar: v.optional(v.nullable(v.boolean())),
  lead_telefono_alternativo: v.optional(v.nullable(v.string())),
})
