import { afterEach, describe, expect, it } from 'vitest'
import { cleanup, render, screen, within, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { PropuestaCitasCRM } from './propuesta'

afterEach(cleanup)

describe('consulta de depósitos desde las inasistencias', () => {
  it('muestra conversión y montos, abre el detalle y conserva el seguimiento existente', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Resultados' }))
    const seguimiento = screen.getByRole('region', { name: 'Seguimiento de inasistencias' })
    const conversion = within(seguimiento).getByRole('region', { name: 'Conversión de inasistencias a depósito' })
    expect(conversion).toHaveTextContent('25% a depósito1 de 4 leads')
    expect(conversion).toHaveTextContent('S/ 35,000')
    expect(conversion).not.toHaveTextContent('US$ 5,000')
    const etapas = within(seguimiento).getByRole('group', { name: 'Etapas de recuperación' })
    const botones = within(etapas).getAllByRole('button')
    for (const [indice, cantidad] of ['4', '3', '1', '1'].entries()) expect(within(botones[indice]!).getByText(cantidad, { exact: true })).toBeInTheDocument()
    await usuario.click(within(seguimiento).getByRole('button', { name: /Depositó/ }))
    const depositantes = within(seguimiento).getByRole('table', { name: 'Personas del flujo de recuperación' })
    expect(within(depositantes).getAllByRole('row')).toHaveLength(2)
    expect(depositantes).not.toHaveTextContent('Esteban Duarte')
    const abrir = within(depositantes).getByRole('button', { name: 'Ver recorrido de Andrea Peralta' })
    await usuario.click(abrir)
    const detalle = screen.getByRole('dialog', { name: 'Andrea Peralta' })
    expect(detalle).toHaveTextContent('DEP-001')
    expect(detalle).toHaveTextContent('04 set. 2026')
    expect(detalle).toHaveTextContent('10:05 Lima')
    const recorrido = within(detalle).getByRole('list', { name: 'Recorrido de la persona' })
    expect(recorrido).toHaveTextContent('ReprogramóRegistro: 01 set. 2026')
    expect(recorrido).toHaveTextContent('Asistió03 set. 2026 · 11:05 Lima')
    await usuario.keyboard('{Escape}')
    await waitFor(() => expect(abrir).toHaveFocus())
    await usuario.click(within(seguimiento).getByRole('button', { name: 'Sin nueva cita' }))
    expect(within(seguimiento).getByRole('table', { name: 'Personas del flujo de recuperación' })).toHaveTextContent('Esteban Duarte')
    await usuario.click(within(seguimiento).getByRole('button', { name: /Reprogramaron/ }))
    expect(within(within(seguimiento).getByRole('table', { name: 'Personas del flujo de recuperación' })).getAllByRole('row')).toHaveLength(4)
  })

  it('aplica asesor y semana a la cohorte y distingue cero depósitos de ninguna inasistencia', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Resultados' }))
    await usuario.click(screen.getByRole('button', { name: /Depositó/ }))
    await usuario.selectOptions(screen.getByLabelText('Analista'), 'valeria')
    expect(screen.getByRole('region', { name: 'Conversión de inasistencias a depósito' })).toHaveTextContent('0% a depósito0 de 1 leads')
    expect(screen.getByText('Ningún lead completó el flujo hasta un depósito confirmado después de asistir.')).toBeInTheDocument()
    await usuario.selectOptions(screen.getByLabelText('Analista'), 'diego')
    expect(screen.getByRole('region', { name: 'Conversión de inasistencias a depósito' })).toHaveTextContent('0% a depósito0 de 1 leads')
    expect(screen.queryByRole('table', { name: 'Personas del flujo de recuperación' })).not.toBeInTheDocument()
    await usuario.selectOptions(screen.getByLabelText('Analista'), 'ana')
    expect(screen.getByRole('region', { name: 'Conversión de inasistencias a depósito' })).toHaveTextContent('100% a depósito1 de 1 leads')
    expect(screen.getByRole('table', { name: 'Personas del flujo de recuperación' })).toHaveTextContent('Andrea Peralta')
    await usuario.selectOptions(screen.getByLabelText('Semana'), '2')
    expect(screen.getByText(/No hay inasistencias con estos filtros/)).toBeInTheDocument()
    expect(screen.getByRole('region', { name: 'Conversión de inasistencias a depósito' })).toHaveTextContent('Sin base de inasistencias')
  })
})
