import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, render, screen, within, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { PropuestaCitasCRM } from './propuesta'

afterEach(() => { cleanup(); vi.unstubAllGlobals() })

const conteo = () => screen.getByTestId('conteo-citas')
const tablaCitas = () => screen.getByRole('table', { name: /Citas de ejemplo que coinciden/ })

describe('propuesta de Citas con componentes reales del CRM', () => {
  it('conserva el mismo conjunto entre las tres vistas y permite abrir las citas del analista', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    await usuario.selectOptions(screen.getByLabelText('Supervisor'), 'Claudia Ríos')
    await usuario.click(screen.getByRole('button', { name: 'Sin resultado 3' }))
    expect(conteo()).toHaveTextContent('3 de 40')
    expect(within(tablaCitas()).getByRole('button', { name: 'Mariana Fuentes' })).toBeInTheDocument()
    await usuario.click(screen.getByRole('tab', { name: 'Agenda' }))
    expect(conteo()).toHaveTextContent('3 de 40')
    expect(screen.getByRole('region', { name: /Citas del 04 set/ })).toBeInTheDocument()
    await usuario.click(screen.getByRole('tab', { name: 'Resultados' }))
    const tabla = screen.getByRole('table', { name: 'Resultados por analista de las citas filtradas' })
    expect(within(within(tabla).getByRole('row', { name: /Total de la consulta/ })).getAllByRole('cell').map(celda => celda.textContent)).toEqual(['3 / 3', '1', '33.3%', '0 de 3', '—'])
    await usuario.click(within(tabla).getByRole('button', { name: 'Valeria León' }))
    expect(screen.getByRole('tab', { name: 'Bandeja comercial' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByLabelText('Analista')).toHaveValue('valeria')
    expect(conteo()).toHaveTextContent('1 de 40')
    await usuario.click(screen.getByRole('button', { name: 'Restablecer consulta' }))
    expect(conteo()).toHaveTextContent('40 de 40')
  })

  it('combina estados y modalidad, quita etiquetas y limpia un analista incompatible con el supervisor', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    await usuario.selectOptions(screen.getByLabelText('Supervisor'), 'Claudia Ríos')
    await usuario.click(screen.getByText('Más filtros'))
    await usuario.click(screen.getByLabelText('Vencida sin resultado'))
    await usuario.click(screen.getByLabelText('Programada'))
    await usuario.selectOptions(screen.getByLabelText('Modalidad'), 'Virtual')
    expect(conteo()).toHaveTextContent('2 de 40')
    await usuario.click(screen.getByRole('button', { name: 'Quitar Modalidad: Virtual' }))
    expect(conteo()).toHaveTextContent('8 de 40')
    await usuario.selectOptions(screen.getByLabelText('Analista'), 'ana')
    await usuario.selectOptions(screen.getByLabelText('Supervisor'), 'Javier Vega')
    expect(screen.getByLabelText('Analista')).toHaveValue('')
    expect(screen.getByRole('option', { name: 'Ana Torres' })).toBeDisabled()
    expect(screen.getByLabelText('Vencida sin resultado')).toBeChecked()
  })

  it('distingue los filtros inválidos de una consulta vacía y separa los importes por moneda', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    await usuario.selectOptions(screen.getByLabelText('Mes'), '2026-08')
    expect(conteo()).toHaveTextContent('0 de 40')
    expect(screen.queryByRole('table', { name: 'Resultados por analista de las citas filtradas' })).not.toBeInTheDocument()
    expect(screen.getByText('No hay citas con esta combinación')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Exportar citas' })).toBeDisabled()
    await usuario.click(screen.getByRole('button', { name: 'Restablecer consulta' }))
    await usuario.click(screen.getByText('Más filtros'))
    expect(screen.getByLabelText('Monto desde')).toBeDisabled()
    await usuario.selectOptions(screen.getByLabelText('Moneda del monto estimado'), 'PEN')
    await usuario.type(screen.getByLabelText('Monto desde'), '80000')
    await usuario.type(screen.getByLabelText('Monto hasta'), '35000')
    expect(screen.getByRole('alert')).toHaveTextContent('El monto mínimo')
    await usuario.selectOptions(screen.getByLabelText('Moneda del monto estimado'), 'USD')
    expect(screen.getByLabelText('Monto desde')).toHaveValue(null)
    expect(screen.getByLabelText('Monto hasta')).toHaveValue(null)
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    await usuario.type(screen.getByRole('searchbox'), 'persona inexistente')
    expect(screen.getByText('No hay citas con esta combinación')).toBeInTheDocument()
    expect(conteo()).toHaveTextContent('0 de 40')
  })

  it('abre la ficha compartida, navega a la agenda y ofrece una guía accesible con retorno de foco', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    await usuario.click(within(tablaCitas()).getByRole('button', { name: 'Mariana Fuentes' }))
    const ficha = screen.getByRole('dialog', { name: 'Mariana Fuentes' })
    expect(within(ficha).getByText('S/ 50,000')).toBeInTheDocument()
    expect(ficha).toHaveAttribute('data-slot', 'sheet')
    await usuario.click(within(ficha).getByRole('button', { name: 'Ubicar en agenda' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(conteo()).toHaveTextContent('1 de 40')
    expect(screen.getByRole('searchbox')).toHaveValue('C-2609-001')
    const agenda = screen.getByRole('tab', { name: 'Agenda' })
    await waitFor(() => expect(agenda).toHaveFocus())
    await usuario.keyboard('{ArrowRight}')
    expect(screen.getByRole('tab', { name: 'Resultados' })).toHaveFocus()
    expect(screen.getByRole('tab', { name: 'Resultados' })).toHaveAttribute('aria-selected', 'true')
    const ayuda = screen.getByRole('button', { name: 'Cómo usar Citas' })
    await usuario.click(ayuda)
    expect(screen.getByRole('dialog', { name: 'Cómo usar Citas' })).toBeInTheDocument()
    await usuario.keyboard('{Escape}')
    await waitFor(() => expect(ayuda).toHaveFocus())
  })

  it('exporta todas las coincidencias aunque la bandeja esté en otra página', async () => {
    const usuario = userEvent.setup()
    let exportado: Blob | undefined
    const crear = vi.fn((blob: Blob) => { exportado = blob; return 'blob:citas-test' })
    vi.stubGlobal('URL', { createObjectURL: crear, revokeObjectURL: vi.fn() })
    const click = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    await usuario.click(screen.getByRole('button', { name: 'Página siguiente' }))
    expect(screen.getByText('Mostrando 9–16 de 40 citas')).toBeInTheDocument()
    await usuario.click(screen.getByRole('button', { name: 'Exportar citas' }))
    expect(click).toHaveBeenCalledOnce()
    const contenido = await new Promise<string>((resolve, reject) => {
      const lector = new FileReader()
      lector.onload = () => resolve(String(lector.result))
      lector.onerror = reject
      lector.readAsText(exportado!)
    })
    expect(contenido.split('\r\n')).toHaveLength(41)
    expect(contenido).toContain('Mariana Fuentes')
    expect(contenido).toContain('Iván Reyes')
    expect(screen.getByText(/Se descargó el CSV con 40 citas/)).toBeInTheDocument()
  })

  it('explica el promedio por lead y abre una nueva cita vinculada aunque quede fuera del filtro de inasistencias', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    expect(screen.queryByRole('region', { name: 'Resumen de las citas filtradas' })).not.toBeInTheDocument()
    await usuario.click(screen.getByRole('tab', { name: 'Resultados' }))
    const tabla = screen.getByRole('table', { name: 'Resultados por analista de las citas filtradas' })
    const ana = within(tabla).getByRole('row', { name: /Ana Torres/ })
    expect(within(ana).getAllByRole('cell').slice(0, 5).map(celda => celda.textContent)).toEqual(['7 / 4', '1.75', '58.3%', '1 de 4', ''])
    await usuario.click(within(ana).getByRole('button', { name: 'Ver detalle por lead de Ana Torres' }))
    const ficha = screen.getByRole('dialog', { name: 'Ana Torres' })
    await usuario.click(within(ficha).getByRole('button', { name: 'Ver citas de Mariana Fuentes' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(conteo()).toHaveTextContent('3 de 40')
    await usuario.click(screen.getByRole('button', { name: 'Restablecer consulta' }))
    await usuario.click(screen.getByRole('button', { name: 'No asistieron 4' }))
    await usuario.click(screen.getByRole('tab', { name: 'Resultados' }))
    const recuperacion = screen.getByRole('region', { name: 'Seguimiento de inasistencias' })
    expect(within(recuperacion).getByRole('button', { name: 'Reprogramaron 3' })).toBeInTheDocument()
    await usuario.click(within(recuperacion).getByRole('button', { name: /Reprogramaron/ }))
    expect(within(within(recuperacion).getByRole('table', { name: 'Personas del flujo de recuperación' })).getAllByRole('row')).toHaveLength(4)
    await usuario.click(within(recuperacion).getByRole('button', { name: 'Ver recorrido de Mónica Silva' }))
    await usuario.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Ver cita vinculada' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Ubicar en agenda' })).toBeInTheDocument())
    await usuario.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Ubicar en agenda' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(conteo()).toHaveTextContent('1 de 40')
    expect(screen.getByRole('tab', { name: 'Agenda' })).toHaveAttribute('aria-selected', 'true')
  })

  it('desde la nueva cita abre las citas del asesor en su mes y restablece los filtros anteriores', async () => {
    const usuario = userEvent.setup()
    render(<PropuestaCitasCRM />)
    await usuario.click(screen.getByRole('tab', { name: 'Bandeja comercial' }))
    await usuario.selectOptions(screen.getByLabelText('Supervisor'), 'Claudia Ríos')
    await usuario.selectOptions(screen.getByLabelText('Semana'), '1')
    await usuario.click(screen.getByRole('button', { name: 'No asistieron 2' }))
    await usuario.click(screen.getByRole('tab', { name: 'Resultados' }))
    await usuario.click(screen.getByRole('button', { name: 'Ver recorrido de Mónica Silva' }))
    await usuario.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Ver cita vinculada' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Citas de Valeria' })).toBeInTheDocument())
    await usuario.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Citas de Valeria' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByLabelText('Supervisor')).toHaveValue('')
    expect(screen.getByLabelText('Semana')).toHaveValue('')
    expect(screen.getByLabelText('Analista')).toHaveValue('valeria')
    expect(conteo()).toHaveTextContent('6 de 40')
    expect(within(tablaCitas()).getByText('C-2609-011 · WhatsApp')).toBeInTheDocument()
  })
})
