import {test,expect} from '@playwright/test'
import {randomUUID,randomInt} from 'node:crypto'
import {readFileSync} from 'node:fs'
import {sql,q} from '../../supabase/scripts/conversion-inversion/banco.mjs'
const fixture=JSON.parse(readFileSync('/private/tmp/avancecorp-conversion-inversion/fixture.json','utf8'))
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aUN0AAAAASUVORK5CYII=','base64')

for(const movil of [false,true])test(`conversión y nueva inversión con backend real, ${movil?'móvil':'escritorio'}`,async({page},info)=>{
  const id=randomUUID(),nombre=`PRUEBA NAVEGADOR ${id.slice(0,8).toUpperCase()}`,dni=String(randomInt(80000000,89999999))
  sql(`insert into crm.leads(id,nombre_completo,telefono,dni,monto_estimado,moneda,etapa,vendedor_id,creado_por,origen)
    values(${q(id)},${q(nombre)},${q('9'+randomInt(10000000,99999999))},${q(dni)},5000,'USD','propuesta_enviada',
      ${q(fixture.usuarios.vendedor.id)},${q(fixture.usuarios.vendedor.id)},'otro')`)
  const escrituras:string[]=[]
  page.on('request',r=>{if(r.method()==='POST'&&/\/rpc\/(preparar_inversion_fn|confirmar_inversion_revisada_fn|convertir_lead)/.test(r.url()))escrituras.push(r.url().split('/').at(-1)!)})
  await page.route('**/*',route=>{
    const u=new URL(route.request().url())
    if(['127.0.0.1','localhost'].includes(u.hostname)||u.protocol==='data:')return route.continue()
    return route.abort('blockedbyclient')
  })
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  await page.locator('#correo').fill(fixture.usuarios.vendedor.email)
  await page.locator('#clave').fill(fixture.password)
  await page.getByRole('button',{name:/^Entrar$/}).click()
  await expect(page.getByRole('button',{name:'Leads',exact:true})).toBeVisible({timeout:20_000})
  await page.getByRole('button',{name:'Leads',exact:true}).click()
  await page.getByLabel('Buscar en la cartera').fill(nombre)
  await page.getByText(nombre,{exact:true}).first().click()
  await page.getByRole('button',{name:'Convertir a cliente',exact:true}).click()
  await expect(page.getByLabel('Documento',{exact:true})).toHaveValue(dni)
  await page.getByRole('button',{name:'Continuar a Nueva inversión'}).click()
  await page.getByRole('button',{name:'Prodelco',exact:true}).click()
  if(movil)await page.setViewportSize({width:390,height:844})
  await expect(page.getByLabel('Moneda',{exact:true})).toHaveValue('USD')
  await expect(page.getByLabel('Capital en dólares (USD)')).toHaveValue('5000')
  await page.getByLabel('Número de operación del depósito').fill(`BROWSER-${id}`)
  await page.getByLabel('Plazo (meses)').fill('12')
  await page.getByLabel('Rentabilidad anual (%)').fill('18')
  await page.getByLabel('Referencia de la inversión').fill('CERTIFICADO NAVEGADOR')
  await page.getByLabel(/Comprobante PDF/).setInputFiles({name:'prueba.png',mimeType:'image/png',buffer:png})
  await page.getByRole('button',{name:'Revisar inversión',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Revisar inversión'})).toBeVisible()
  expect(sql(`select etapa from crm.leads where id=${q(id)}`)).toBe('propuesta_enviada')
  const solicitud=sql(`select id from crm.inversion_solicitudes where lead_origen_id=${q(id)}`)
  expect(solicitud).toBeTruthy()
  await page.screenshot({path:info.outputPath('revision-inicial.png'),fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.getByRole('button',{name:'Cerrar y continuar después'}).click()
  expect(sql(`select etapa from crm.leads where id=${q(id)}`)).toBe('propuesta_enviada')
  await page.getByRole('button',{name:'Convertir a cliente',exact:true}).click()
  await page.getByRole('button',{name:'Continuar a Nueva inversión'}).click()
  await expect(page.getByRole('heading',{name:'Revisar inversión'})).toBeVisible()
  await page.getByLabel(/Comprobante PDF/).setInputFiles({name:'prueba.png',mimeType:'image/png',buffer:png})
  let cargaInterrumpida=false
  if(!movil)await page.route('**/storage/v1/object/f4-comprobantes/**',async route=>{
    if(route.request().method()==='POST'&&!cargaInterrumpida){
      const respuesta=await route.fetch();expect(respuesta.ok()).toBe(true)
      cargaInterrumpida=true;return route.abort('failed')
    }
    return route.continue()
  })
  await page.getByRole('button',{name:'Confirmar inversión',exact:true}).click()
  if(!movil){
    await expect(page.getByRole('alert')).toContainText('No se pudo cargar el comprobante')
    expect(cargaInterrumpida).toBe(true)
    await page.getByRole('button',{name:'Confirmar inversión',exact:true}).click()
  }
  await expect(page.getByRole('heading',{name:'Inversión confirmada'})).toBeVisible()
  expect(sql(`select etapa from crm.leads where id=${q(id)}`)).toBe('convertido')
  expect(sql(`select count(*) from crm.inversion_solicitudes where lead_origen_id=${q(id)}`)).toBe('1')
  expect(escrituras.filter(x=>x==='preparar_inversion_fn')).toHaveLength(1)
  await page.screenshot({path:info.outputPath('conversion-confirmada.png'),fullPage:true})
  await page.getByRole('button',{name:'Volver a la ficha'}).click()
  await page.getByRole('button',{name:'Ver inversión y bienvenida'}).click()
  await expect(page.getByRole('heading',{name:'Inversión confirmada'})).toBeVisible()
  await expect(page.getByLabel('Documento',{exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Volver a la ficha'}).click()
  await page.keyboard.press('Escape')
  if(movil)await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('button',{name:'Mi cartera',exact:true}).click()
  await page.getByLabel('Buscar persona').fill(nombre)
  await page.getByRole('button',{name:`Abrir ficha de ${nombre}`}).click()
  await page.getByRole('button',{name:'Registrar nueva inversión',exact:true}).click()
  await page.getByRole('button',{name:'Prodelco',exact:true}).click()
  await page.getByLabel('Moneda',{exact:true}).selectOption('USD')
  await page.getByLabel('Capital en dólares (USD)').fill('5000')
  await page.getByLabel('Número de operación del depósito').fill(`BROWSER-AD-${id}`)
  await page.getByLabel('Plazo (meses)').fill('12')
  await page.getByLabel('Rentabilidad anual (%)').fill('18')
  await page.getByLabel('Referencia de la inversión').fill('CERTIFICADO NAVEGADOR ADICIONAL')
  await page.getByLabel(/Comprobante PDF/).setInputFiles({name:'prueba.png',mimeType:'image/png',buffer:png})
  await page.getByRole('button',{name:'Revisar inversión',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar inversión',exact:true}).click()
  // Cartera puede volver a montar su ficha al refrescar capacidades. El hecho
  // confirmado y el resumen visible son el criterio duradero de este recorrido.
  await expect.poll(()=>sql(`select count(*) from crm.inversiones where inversionista_id=(select inversionista_id from crm.leads where id=${q(id)})`)).toBe('2')
  const volver=page.getByRole('button',{name:'Volver a la ficha'})
  if(await volver.isVisible())await volver.click()
  await expect(page.getByText('2 inversiones en esta ficha',{exact:true})).toBeVisible()
  expect(escrituras.filter(x=>x==='preparar_inversion_fn')).toHaveLength(2)
  expect(escrituras.some(x=>x.startsWith('convertir_lead'))).toBe(false)
  expect(sql(`select count(*) from crm.inversiones where inversionista_id=(select inversionista_id from crm.leads where id=${q(id)})`)).toBe('2')
  expect(sql(`select count(*) from crm.inversiones where inversionista_id=(select inversionista_id from crm.leads where id=${q(id)}) and es_primera_conversion`)).toBe('1')
})
